# Site settings
title: Hi,CUGer!
subtitle: by HTML5 UP
email: bestclover14580@foxmail.com
description: just a simple website for cugers.
baseurl: # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
author: CloverYang
street_address: 洪山区鲁磨路388号
city: 武汉
state: CN
zip_code: 430003
country: China
phone: 643458793（电话保密~联系QQ吧）

# Social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# Sass building
sass:
    sass_dir: _sass
    
# Build settings
markdown: kramdown

theme: jekyll-theme-slate
